flowchart TD
    A([Start]) --> B[/Admin and Staff Dashboard/]
    B --> C[Manage Applications]
    C --> D[Review Documents]
    D --> E[Update Status and Notify]
    E --> F[Manage Interview Schedule]
    F --> G[Manage Scholar Records]
    G --> H[Add Disbursement]
    H --> I[Manage Users]
    I --> J[Send SMS]
    J --> K([End])
