@startuml
title LGU Scholarship System Flowchart - Applicant Process

skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Arial
skinparam defaultFontSize 13
skinparam backgroundColor white
skinparam ArrowColor black
skinparam linetype ortho

start

:Applicant Dashboard;
:Manage Personal Info;
:Submit Application;
:Upload Documents;
if (Documents complete?) then (No)
  :Resubmit Documents;
endif

:Track Status;
:Attend Interview;
:Upload SOA;
:Claim Payout;

stop
@enduml
